DROP TABLE IF EXISTS `playerbots_guild_names`;
CREATE TABLE `playerbots_guild_names` (
                                          `name_id` INT(11) NOT NULL AUTO_INCREMENT UNIQUE,
                                          `name` varchar(24) NOT NULL UNIQUE,
                                          PRIMARY KEY (`name_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Playerbot guild names';

INSERT INTO `playerbots_guild_names` VALUES
(NULL, '留香阁'),
(NULL, '浪漫烟雨城'),
(NULL, '梦海之巅'),
(NULL, '第七封印'),
(NULL, '艺馨轩'),
(NULL, '玫瑰当铺'),
(NULL, '皇都玫瑰花园'),
(NULL, '相思红人馆'),
(NULL, '誓永血盟'),
(NULL, '清风怡江'),
(NULL, '陌陌小阁'),
(NULL, '摘星阁'),
(NULL, '倚窗听雨'),
(NULL, '半盏流年'),
(NULL, '雪归殇'),
(NULL, '银翼之辉'),
(NULL, '风华竹韵'),
(NULL, '怡海风岚'),
(NULL, '傲影山庄'),
(NULL, '安炫世家'),
(NULL, '花风狂骨'),
(NULL, '清梦空留'),
(NULL, '宅腐同萌'),
(NULL, '夜宫'),
(NULL, '半耳弥音'),
(NULL, '江湖莱'),
(NULL, '堇年纸鸢'),
(NULL, '抱影无眠'),
(NULL, '繁华落幕'),
(NULL, '桃花坞'),
(NULL, '布拉格◇神话'),
(NULL, '雨丝文艺社团'),
(NULL, '珈蓝神殿'),
(NULL, '逍遥営'),
(NULL, '弈剑听雨阁'),
(NULL, '墨谭阁'),
(NULL, '秋水无痕'),
(NULL, '晓月燃霜'),
(NULL, '逐鹿天下'),
(NULL, '幻月洞府'),
(NULL, '布拉格神话'),
(NULL, '萌小盟'),
(NULL, '梦离醒悟'),
(NULL, '木槿暖夏'),
(NULL, '秋夕遗梦'),
(NULL, '花容天下'),
(NULL, '降世天谴'),
(NULL, '郇山隐修会'),
(NULL, '天意缘散'),
(NULL, '泷魂'),
(NULL, '醉意江湖'),
(NULL, '冰凝城夏'),
(NULL, '幽水雅阁'),
(NULL, '梵音阁'),
(NULL, '傲世听雨轩'),
(NULL, '魂魄皇朝'),
(NULL, '星之恋'),
(NULL, '永恒霁忆'),
(NULL, '湮羽澜约'),
(NULL, '听雨阁'),
(NULL, '冰轮霜天'),
(NULL, '水月洞天'),
(NULL, '影阁'),
(NULL, '剑啸天下'),
(NULL, '同萌会'),
(NULL, '末世名流'),
(NULL, '无忧小筑'),
(NULL, '暗月降临'),
(NULL, '上帝审判'),
(NULL, '闲人居'),
(NULL, '倾乱红尘'),
(NULL, '倾尽天下'),
(NULL, '卧听潇雨'),
(NULL, '梦染江山'),
(NULL, '失落之会'),
(NULL, '清幽阁'),
(NULL, '梵音战阁'),
(NULL, '无涯客栈'),
(NULL, '涵香阁'),
(NULL, '悠林飘雪'),
(NULL, '天空楼'),
(NULL, '冷月轩'),
(NULL, '冰雪之幻城'),
(NULL, '穹顶之上'),
(NULL, '圣世轩辕'),
(NULL, '真武苑'),
(NULL, '舞天之风'),
(NULL, '苍羽宇'),
(NULL, '纵横逍遥'),
(NULL, '水幻盟'),
(NULL, '天道院'),
(NULL, '逸雅轩'),
(NULL, '琴剑山庄'),
(NULL, '追魂宫'),
(NULL, '独领天下'),
(NULL, '光之翼族'),
(NULL, '樱花雨'),
(NULL, '血鸦堡'),
(NULL, '风雅颂'),
(NULL, '云端梦之郡'),
(NULL, '落花坞'),
(NULL, '灵霄轩'),
(NULL, '白凤府'),
(NULL, '清清茶烟挽'),
(NULL, '飞星谷'),
(NULL, '潇湘阁'),
(NULL, '翠羽世家'),
(NULL, '听雨品茗阁'),
(NULL, '破元谷'),
(NULL, '茶醉书香'),
(NULL, '君风临江山'),
(NULL, '鸿蒙轩'),
(NULL, '断魂殿'),
(NULL, '夏残夜未央'),
(NULL, '弈缘仙阁'),
(NULL, '天武阁'),
(NULL, '狂浪剑派'),
(NULL, '墨尘花舞影'),
(NULL, '洛洛微光暖'),
(NULL, '醉若晓残风'),
(NULL, '水墨汀'),
(NULL, '潇潇沐雨寒'),
(NULL, '逍遥院'),
(NULL, '疾雷亭'),
(NULL, '四方剑派'),
(NULL, '醉仙霖宫'),
(NULL, '剑上江南'),
(NULL, '夺魄刹'),
(NULL, '听雪楼'),
(NULL, '芸芸众生'),
(NULL, '乱世繁华'),
(NULL, '紫月阁'),
(NULL, '烟雨楼台'),
(NULL, '聚贤山庄'),
(NULL, '烟雨阁'),
(NULL, '残紫轩'),
(NULL, '情缘阁'),
(NULL, '泼墨斋'),
(NULL, '苍龙之穹噤'),
(NULL, '光明派'),
(NULL, '擎天殿'),
(NULL, '幻之帝国'),
(NULL, '天翔世家'),
(NULL, '水云天'),
(NULL, '夏沫花落语'),
(NULL, '青云小筑'),
(NULL, '玄霜亭'),
(NULL, '风雪国度'),
(NULL, '韵墨草堂'),
(NULL, '神梦道'),
(NULL, '破元组'),
(NULL, '逸笑悠然'),
(NULL, '冰雪紫魂'),
(NULL, '凶魔宫'),
(NULL, '万圣岩'),
(NULL, '大衍坊'),
(NULL, '镰鼬教'),
(NULL, '涡卷坊'),
(NULL, '兽王刹'),
(NULL, '如来观'),
(NULL, '沧海观'),
(NULL, '无量祠'),
(NULL, '屠仙庙'),
(NULL, '无双宫'),
(NULL, '烈火旗'),
(NULL, '斗龙帮'),
(NULL, '夺魂斋'),
(NULL, '墨龙阵'),
(NULL, '元始堡'),
(NULL, '巨鲸狱'),
(NULL, '柳絮会'),
(NULL, '歃血盟'),
(NULL, '屠妖教'),
(NULL, '易筋刹'),
(NULL, '光明阙'),
(NULL, '悟禅山'),
(NULL, '无为党'),
(NULL, '尸骨旗'),
(NULL, '大悲门'),
(NULL, '天罗斋'),
(NULL, '黑暗护卫队'),
(NULL, '艾斯利东部王国'),
(NULL, '黑寡妇军团'),
(NULL, '拉特蒙的末日'),
(NULL, '末日的绝响'),
(NULL, '红色自卫队'),
(NULL, '永恒领域'),
(NULL, '暗黑骑士军团'),
(NULL, '奥兰维克的秩序'),
(NULL, '白银骑士团'),
(NULL, '奥巴马的禁卫军'),
(NULL, '御林军八佰伴'),
(NULL, '解放军第二炮兵部队'),
(NULL, '锦衣卫'),
(NULL, '死神第比利斯的诅咒'),
(NULL, '阿波罗之手'),
(NULL, '你妹妹爱我'),
(NULL, '刘德华的杀戮'),
(NULL, '林彪第四野战军'),
(NULL, '蒙古铁骑'),
(NULL, '唐朝'),
(NULL, '独立团'),
(NULL, '艾泽拉斯烟草专卖局'),
(NULL, '皇家学院'),
(NULL, '首席流氓集团'),
(NULL, '无风险投资公司'),
(NULL, '夜空之歌'),
(NULL, '燃烧军团'),
(NULL, '龙神'),
(NULL, '精武体操会'),
(NULL, '基地组织'),
(NULL, '改革委员会'),
(NULL, '十字路口街道办事处'),
(NULL, '阿尔萨斯的爷爷奶奶们'),
(NULL, '如果公会名字起的太长躲在树后面会被看见'),
(NULL, '梦境之树护卫队'),
(NULL, '彩虹之湖管理公司'),
(NULL, '永恒之井警卫军'),
(NULL, '荒芜之地自卫队'),
(NULL, '诅咒之地军团'),
(NULL, '贫瘠之地的土匪们'),
(NULL, '凄凉之地秩序'),
(NULL, '黑暗之领域'),
(NULL, '风暴之眼的狂徒们'),
(NULL, '激流之傲的骑士军团'),
(NULL, '迷雾之海盗军团'),
(NULL, '自由之风的守卫军'),
(NULL, '黄金之路城管大队'),
(NULL, '幽魂之地的地头蛇'),
(NULL, '金色平原之苍狼'),
(NULL, '翡翠梦境魔导士'),
(NULL, '尘风峡谷骑士军'),
(NULL, '日落沼泽的尘埃'),
(NULL, '月光林地投资公司'),
(NULL, '千针石林办事处'),
(NULL, '甜水绿洲守卫军团'),
(NULL, '被遗忘的海贼团'),
(NULL, '永歌森林守卫军'),
(NULL, '暮色森林野战队'),
(NULL, '燃烧平原放火小分队'),
(NULL, '冰焰猎手'),
(NULL, '血色暗骑'),
(NULL, '黑暗毁灭者'),
(NULL, '闪电突袭者'),
(NULL, '幽影剑士'),
(NULL, '血刃猎手'),
(NULL, '暮夜行者'),
(NULL, '暗影噬灵者'),
(NULL, '魂刃刺客'),
(NULL, '无尽法师'),
(NULL, '魅影暗刺者'),
(NULL, '灵魂剑客'),
(NULL, '血色狩猎者'),
(NULL, '猛火烈焰'),
(NULL, '混沌火焰'),
(NULL, '吸血鬼之影'),
(NULL, '血刃舞者'),
(NULL, '冰霜统领'),
(NULL, '狂龙之骑'),
(NULL, '暮色刺客'),
(NULL, '毁灭之炎'),
(NULL, '冰雪女咒'),
(NULL, '血域幻影'),
(NULL, '狂野战雷'),
(NULL, '翡翠龙骑'),
(NULL, '影子斩杀者'),
(NULL, '黑暗帝君'),
(NULL, '妖术术士'),
(NULL, '冰焰征服者'),
(NULL, '血影幽魄'),
(NULL, '狂怒猎狼'),
(NULL, '虚幻侍刺'),
(NULL, '雷霆闪电'),
(NULL, '黑暗至尊'),
(NULL, '烈焰霸主'),
(NULL, '剑舞红颜'),
(NULL, '灵魂狂战'),
(NULL, '风暴怒吼者'),
(NULL, '寒焰剑客'),
(NULL, '烈火龙骑'),
(NULL, '冰影魔法师'),
(NULL, '闪电术士'),
(NULL, '暗影幽魂'),
(NULL, '绝影猎手'),
(NULL, '深寒女皇'),
(NULL, '血裔刀客'),
(NULL, '梦魇战士'),
(NULL, '雷霆圣骑士'),
(NULL, '烈焰魔导员'),
(NULL, '冰霜女主'),
(NULL, '幽灵剑客'),
(NULL, '血之黑骑士'),
(NULL, '狂风魔法师'),
(NULL, '幻影刺杀者'),
(NULL, '闪电猛豹'),
(NULL, '铁血战士'),
(NULL, '血咒暗法师'),
(NULL, '孤独剑豪'),
(NULL, '无尽狂怒'),
(NULL, '巨岩战斧手'),
(NULL, '冰火灾祸者'),
(NULL, '幻影雇佣兵'),
(NULL, '狂风风雨'),
(NULL, '战场统帅'),
(NULL, '魔法虚空师'),
(NULL, '光明使徒'),
(NULL, '血刃猎人'),
(NULL, '黑翼毁灭者'),
(NULL, '暗影夜魔'),
(NULL, '无尽奥术士'),
(NULL, '闪电战车'),
(NULL, '冰封女魔'),
(NULL, '灵魂剑使'),
(NULL, '烈焰风暴'),
(NULL, '血色猎魂者'),
(NULL, '冥夜影刀'),
(NULL, '灼热烈焰'),
(NULL, '血腥舞姬'),
(NULL, '野性狂焰'),
(NULL, '龙骑霸主'),
(NULL, '梦幻'),
(NULL, '影之狂鬼'),
(NULL, '熔岩烈焰'),
(NULL, '寒冰雪女'),
(NULL, '野蛮狂猛者'),
(NULL, '龙骑守护者'),
(NULL, '夜幕幻影'),
(NULL, '黑暗帝王者'),
(NULL, '秘术幻师'),
(NULL, '烈火征服者'),
(NULL, '血魂幽影'),
(NULL, '狂战狼骑'),
(NULL, '虚幻暗刺者'),
(NULL, '闪电幽魂'),
(NULL, '黑暗至高者'),
(NULL, '烈焰之主宰'),
(NULL, '血影舞姬'),
(NULL, '雷霆狂怒战士'),
(NULL, '冰霜领主'),
(NULL, '梦幻幽影杀手'),
(NULL, '黑暗影刺者'),
(NULL, '火冰法师'),
(NULL, '冰雪幻舞者'),
(NULL, '鲜血暗魅'),
(NULL, '幽光骑士'),
(NULL, '炎焰魔术师'),
(NULL, '幽灵剑豪'),
(NULL, '冰火追猎者'),
(NULL, '血色暗骑者'),
(NULL, '狂风魔导师'),
(NULL, '黑暗毁灭使者'),
(NULL, '闪电迅猛兽'),
(NULL, '血法师'),
(NULL, '孤独剑侠'),
(NULL, '怒火无尽者'),
(NULL, '巨石战斧战士'),
(NULL, '冰焰剑骑'),
(NULL, '幽影刺杀'),
(NULL, '战场主宰'),
(NULL, '魔法虚空法师'),
(NULL, '无情暗刺杀者'),
(NULL, '冰血要塞'),
(NULL, '血刃暗影'),
(NULL, '暗影猎魔者'),
(NULL, '魂刃剑客'),
(NULL, '无尽奥术使者'),
(NULL, '灵魂剑师'),
(NULL, '烈焰风魔'),
(NULL, '冥夜暗影刀客'),
(NULL, '炽焰烈火'),
(NULL, '寒冰女神'),
(NULL, '血红舞姬'),
(NULL, '野性狂怒战士'),
(NULL, 'Sweet Bear'),
(NULL, 'Sword of Lost Evil'),
(NULL, 'Tainted Bunnies'),
(NULL, 'Talon of the Eclectic'),
(NULL, 'Team Kingdom'),
(NULL, 'Team United'),
(NULL, 'Tears of Eternal Kitties'),
(NULL, 'Tears of Phantom Druids'),
(NULL, 'Templar of Raid Dodgers'),
(NULL, 'Templars of Plagueware'),
(NULL, 'Terra Totem'),
(NULL, 'Terra War'),
(NULL, 'The Abiem'),
(NULL, 'The Aceofchaos'),
(NULL, 'The Afterlife'),
(NULL, 'The Aggression'),
(NULL, 'The Alliance of Dark'),
(NULL, 'The Altimate'),
(NULL, 'The Ancona Fire'),
(NULL, 'The Apocalypse'),
(NULL, 'The Arcane Monkey'),
(NULL, 'The Army of Spartans'),
(NULL, 'The Avalon'),
(NULL, 'The Avengers of Shining'),
(NULL, 'The Azure Gangstaz'),
(NULL, 'The Battlegnome'),
(NULL, 'The Black Hand Haven'),
(NULL, 'The Blackdraygon'),
(NULL, 'The Blackout'),
(NULL, 'The Blade'),
(NULL, 'The Blades of Caer Eel'),
(NULL, 'The Blades of Onyxia'),
(NULL, 'The Blood Red Violence'),
(NULL, 'The Blood of Red Powers'),
(NULL, 'The Bloodycrusaders'),
(NULL, 'The Blues Azeroth'),
(NULL, 'The Blues Grimfang'),
(NULL, 'The Bluethunder'),
(NULL, 'The Bonds of Arcane'),
(NULL, 'The Brimstone'),
(NULL, 'The Broken Chaos'),
(NULL, 'The Brood of Unknown'),
(NULL, 'The Burning Dog Firewall'),
(NULL, 'The Cabal'),
(NULL, 'The Cake Gankers'),
(NULL, 'The Cannabuddies'),
(NULL, 'The Circle of Shadow'),
(NULL, 'The Clan Blackwatch Few'),
(NULL, 'The Clan Cats'),
(NULL, 'The Clan Knights'),
(NULL, 'The Clean Combinations'),
(NULL, 'The Clean Up Guard'),
(NULL, 'The Council of Dark'),
(NULL, 'The Covenant'),
(NULL, 'The Crimson Guild'),
(NULL, 'The Crimson Marbock'),
(NULL, 'The Crusaders of Horde'),
(NULL, 'The Crusaders of Seksoni'),
(NULL, 'The Cult of Clan Brigade'),
(NULL, 'The Cult of the Pink'),
(NULL, 'The Daggers of the Vile'),
(NULL, 'The Dark'),
(NULL, 'The Dark Dogs'),
(NULL, 'The Dark Pain'),
(NULL, 'The Darkfall'),
(NULL, 'The Darkside Vanguard'),
(NULL, 'The Darkside of Initium'),
(NULL, 'The Daughters of the Elite'),
(NULL, 'The Daytripper'),
(NULL, 'The Deadfriends'),
(NULL, 'The Defiant'),
(NULL, 'The Dont Overwhelming'),
(NULL, 'The Doom Pasta'),
(NULL, 'The Dragon Redeye'),
(NULL, 'The Dragons Flame'),
(NULL, 'The Dreadlords'),
(NULL, 'The Dublainn Crown'),
(NULL, 'The Durban Protecters'),
(NULL, 'The Echoes of Goldshire'),
(NULL, 'The Elit of Dark Elune'),
(NULL, 'The Emissaries of Furiou'),
(NULL, 'The Eternal Chaos'),
(NULL, 'The Eternus'),
(NULL, 'The Exiie'),
(NULL, 'The Expendable Shadow'),
(NULL, 'The Faith of Desert'),
(NULL, 'The Family Misfits'),
(NULL, 'The Fere Darkness'),
(NULL, 'The Final Tears'),
(NULL, 'The Forsaken Boochies'),
(NULL, 'The Gates of the Bloody'),
(NULL, 'The Gnomes Lordaero'),
(NULL, 'The Gods of Blackscar'),
(NULL, 'The Gods of Twilight'),
(NULL, 'The Gold Fighters'),
(NULL, 'The Guardian Thieves'),
(NULL, 'The Guardians of Gnome'),
(NULL, 'The Hands of Redridge'),
(NULL, 'The Hawk'),
(NULL, 'The Hearts Images'),
(NULL, 'The Hellborn Die'),
(NULL, 'The Heroes Plague'),
(NULL, 'The Horde Farmer'),
(NULL, 'The Horde Honor'),
(NULL, 'The Hotpocket'),
(NULL, 'The Ignis Prophecy'),
(NULL, 'The Illuminatie'),
(NULL, 'The Immortal League'),
(NULL, 'The Independant'),
(NULL, 'The Infragilis Legion'),
(NULL, 'The Jag'),
(NULL, 'The Jookmaster'),
(NULL, 'The Kataclysm'),
(NULL, 'The Knight'),
(NULL, 'The Knightelf'),
(NULL, 'The Knights Thorn'),
(NULL, 'The Knights of Gods Fury'),
(NULL, 'The Knights of Lost Peon'),
(NULL, 'The Knights of Mortal'),
(NULL, 'The Knights of Samurai'),
(NULL, 'The Kobra'),
(NULL, 'The Leaders of Evil'),
(NULL, 'The Leaders of Life'),
(NULL, 'The League of Red Knight'),
(NULL, 'The Legacy Meathooks'),
(NULL, 'The Legion of the Blue'),
(NULL, 'The Legion of Death'),
(NULL, 'The Lemmings of Flaming'),
(NULL, 'The Let Blood Gamer'),
(NULL, 'The Light'),
(NULL, 'The Little Hunters'),
(NULL, 'The Lords of Vae Knight'),
(NULL, 'The Mercenaries'),
(NULL, 'The Midieval Vanguard'),
(NULL, 'The Might of Dark Tong'),
(NULL, 'The Mithril Justice'),
(NULL, 'The Mithril Pepsi'),
(NULL, 'The Mjollnir'),
(NULL, 'The Moo Licht'),
(NULL, 'The Morgantis'),
(NULL, 'The Mulletmen'),
(NULL, 'The Necrontyr of Eternal'),
(NULL, 'The Nedrage Kills'),
(NULL, 'The Night'),
(NULL, 'The Nightfall'),
(NULL, 'The Ninja Heroes'),
(NULL, 'The Order of Gold'),
(NULL, 'The Order of Warcraft'),
(NULL, 'The Order of Warsong'),
(NULL, 'The Over Louder'),
(NULL, 'The Overlord'),
(NULL, 'The Pants'),
(NULL, 'The Pie'),
(NULL, 'The Pretectors'),
(NULL, 'The Project Disease'),
(NULL, 'The Psychotics'),
(NULL, 'The Puggers'),
(NULL, 'The Pyreborne'),
(NULL, 'The Queen of Meow'),
(NULL, 'The Red Hood Thunder'),
(NULL, 'The Reign of Uber Enigma'),
(NULL, 'The Resurrection'),
(NULL, 'The Ring of Honor'),
(NULL, 'The Ropetown'),
(NULL, 'The Royal Militia Blanco'),
(NULL, 'The Samurai Banda'),
(NULL, 'The Sanity'),
(NULL, 'The Sauce'),
(NULL, 'The Schoolyard Reapers'),
(NULL, 'The Secrets of Hehog'),
(NULL, 'The Seers'),
(NULL, 'The Servants of Cyclone'),
(NULL, 'The Seven'),
(NULL, 'The Shadow Gate'),
(NULL, 'The Shadow Misfits'),
(NULL, 'The Shadow of Ninja Pain'),
(NULL, 'The Shadowborn'),
(NULL, 'The Shizam'),
(NULL, 'The Shockers'),
(NULL, 'The Shriek of Nightmare'),
(NULL, 'The Silent Grunts'),
(NULL, 'The Silent Legion'),
(NULL, 'The Skunkdesigns'),
(NULL, 'The Sorrow'),
(NULL, 'The Souls of Azeroth Old'),
(NULL, 'The Spazler'),
(NULL, 'The Squirrels'),
(NULL, 'The Stringville'),
(NULL, 'The Stronghold of Reds'),
(NULL, 'The Tha Handlers'),
(NULL, 'The Thieves of Moral'),
(NULL, 'The Thorium Claw'),
(NULL, 'The Thread'),
(NULL, 'The Thule'),
(NULL, 'The Thunderslayers'),
(NULL, 'The True Wow'),
(NULL, 'The Trusted Minions'),
(NULL, 'The Twilight Rangers'),
(NULL, 'The Tyraels Aggression'),
(NULL, 'The Ultimates'),
(NULL, 'The Unforgiven Heresy'),
(NULL, 'The Unholy Bards'),
(NULL, 'The Unsung Efficiency'),
(NULL, 'The Valley of the Demon'),
(NULL, 'The Valor'),
(NULL, 'The Violent Chaos'),
(NULL, 'The Virus Eternal'),
(NULL, 'The War'),
(NULL, 'The Warsong Gnomeregan'),
(NULL, 'The Westcoast'),
(NULL, 'The Wicked'),
(NULL, 'The Will of Chronicles'),
(NULL, 'The Windsword Nightmare'),
(NULL, 'The Wings of Oxy Claw'),
(NULL, 'The Wrath of Elton'),
(NULL, 'The Wut'),
(NULL, 'The Yoricks Assassins'),
(NULL, 'The Zeksonic Thieves'),
(NULL, 'Theramore Azeroth'),
(NULL, 'Thirstquencher Chaos'),
(NULL, 'Thralls Caribous'),
(NULL, 'Three Alive'),
(NULL, 'Titans of Blood Sun'),
(NULL, 'Torvus Dragons'),
(NULL, 'Tower of the Little'),
(NULL, 'True Team'),
(NULL, 'Tul Inc'),
(NULL, 'Twinks of Cold Club'),
(NULL, 'Twinks of Hidden Venture'),
(NULL, 'Ultimate Rules'),
(NULL, 'Undead Kingdom'),
(NULL, 'Unforgiven Destiny'),
(NULL, 'Unguilded War'),
(NULL, 'Unholy Cats'),
(NULL, 'Unholy Teeth'),
(NULL, 'Union of Burning Prz'),
(NULL, 'Unusual Guard'),
(NULL, 'Valiant Riderz'),
(NULL, 'Vanguard Omen'),
(NULL, 'Vanguard Redeemers'),
(NULL, 'Vanguard of Teutonic'),
(NULL, 'Vengeful Mayhem'),
(NULL, 'Verata Blackflame'),
(NULL, 'Vicious Renegade'),
(NULL, 'Vile Dead'),
(NULL, 'Voodoo Hearth'),
(NULL, 'War Legion'),
(NULL, 'Warlockian Tree'),
(NULL, 'Warlords of Kungfu Army'),
(NULL, 'Warriors of Happy Death'),
(NULL, 'Warriors of the Tundra'),
(NULL, 'Warsong Insanity'),
(NULL, 'Waste of Grey Death'),
(NULL, 'Wayfarers of Maple Leaf'),
(NULL, 'Wayward Agenda'),
(NULL, 'Web of Forgoten Warfare'),
(NULL, 'Wet Guard'),
(NULL, 'Wild Fire'),
(NULL, 'Will of the Forgotten'),
(NULL, 'Winds of Steve Irwin'),
(NULL, 'Wings of Emerald Minions'),
(NULL, 'Wintermane Good'),
(NULL, 'Witchhunters of Chaos'),
(NULL, 'With Sea'),
(NULL, 'Wrath of the Horde Troop'),
(NULL, 'Wtf Losers'),
(NULL, 'Xcalibur of Shogunz Depo'),
(NULL, 'Xelium Determination');
